#pragma once

namespace GameAttributes {
	const int   GAME_GRID_ROW_COUNT = 20;
	const int   GAME_GRID_COLUMN_COUNT = 10;
	const float SQUARE_HEIGHT = 30;
	const float SQUARE_WIDTH = SQUARE_HEIGHT;
	const float LINE_WIDTH = 1;
	const float GAME_GRID_TOTAL_WIDTH = GAME_GRID_COLUMN_COUNT * (SQUARE_WIDTH + LINE_WIDTH);
	const float GAME_GRID_TOTAL_HEIGHT = GAME_GRID_ROW_COUNT * (SQUARE_HEIGHT + LINE_WIDTH);
	const float SCREEN_ITEM_PADDING = 60;
	const float PREVIEW_BOX_BORDER_WIDTH = 30;

	const float PREVIEW_BOX_WIDTH = 4 * (SQUARE_WIDTH + LINE_WIDTH) + (2 * PREVIEW_BOX_BORDER_WIDTH);
	const float GRID_SIDE_SPACE_WIDTH = PREVIEW_BOX_WIDTH + 2 * SCREEN_ITEM_PADDING;

	const int MINI_BOX_ROW_COUNT = 2;
	const int MINI_BOX_COLUMN_COUNT = 4;
	const int PREVIEW_COUNT = 3;
	const float PREVIEW_BOX_HEIGHT = (PREVIEW_COUNT * MINI_BOX_ROW_COUNT) * (SQUARE_HEIGHT + LINE_WIDTH) + ((PREVIEW_COUNT + 1) * PREVIEW_BOX_BORDER_WIDTH);
	const int GAME_PIECE_SHAPE_COUNT = 7;

	const float   WINDOW_WIDTH = GAME_GRID_TOTAL_WIDTH + 2 * GRID_SIDE_SPACE_WIDTH;
	const float   WINDOW_HEIGHT = GAME_GRID_TOTAL_HEIGHT + 2 * SCREEN_ITEM_PADDING;

	const float GAME_GRID_ANCHOR_X = (WINDOW_WIDTH - GAME_GRID_TOTAL_WIDTH) / 2;
	const float GAME_GRID_ANCHOR_Y = SCREEN_ITEM_PADDING;


	const float GAME_PREVIEW_BOX_X = GAME_GRID_ANCHOR_X + GAME_GRID_TOTAL_WIDTH + SCREEN_ITEM_PADDING;
	const float GAME_PREVIEW_BOX_Y = GAME_GRID_ANCHOR_Y +(SQUARE_HEIGHT + LINE_WIDTH) * 2;

	const float STATS_BOX_X = SCREEN_ITEM_PADDING;
	const float STATS_BOX_Y = GAME_PREVIEW_BOX_Y;

	const float STATS_BOX_WIDTH = PREVIEW_BOX_WIDTH;

}
